export const WAHA_WEBHOOKS: Record<string, string> = {
  'session.status': 'Session status changed',
  'message': 'New message received',
  'message.reaction': 'Message reaction',
  'message.any': 'Any message event',
  'message.ack': 'Message acknowledgment',
  'message.ack.group': 'Message group acknowledgment',
  'message.waiting': 'Message waiting',
  'message.revoked': 'Message revoked',
  'message.edited': 'Message edited',
  'state.change': 'State change',
  'group.join': 'Group join',
  'group.leave': 'Group leave',
  'group.v2.join': 'Group v2 join',
  'group.v2.leave': 'Group v2 leave',
  'group.v2.update': 'Group v2 update',
  'group.v2.participants': 'Group v2 participants',
  'presence.update': 'Presence update',
  'poll.vote': 'Poll vote',
  'poll.vote.failed': 'Poll vote failed',
  'chat.archive': 'Chat archive',
  'call.received': 'Call received',
  'call.accepted': 'Call accepted',
  'call.rejected': 'Call rejected',
  'label.upsert': 'Label upsert',
  'label.deleted': 'Label deleted',
  'label.chat.added': 'Label chat added',
  'label.chat.deleted': 'Label chat deleted',
  'event.response': 'Event response',
  'event.response.failed': 'Event response failed',
  'engine.event': 'Engine event',
};
